baseURL = "https://CheolKyunYU.github.io/ck.log/"
locale = "ko-KR"
title = "CK log"
theme = "PaperMod"

# PaperMod Search
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  env = "production"
  title = "CK log"
  description = "IT systems engineer CK log"
  author = "CK"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true

[languages.ko]
  label = "Korean"
  weight = 1
  [languages.ko.menu]
    [[languages.ko.menu.main]]
      identifier = "posts"
      name = "Posts"
      url = "/posts/"
      weight = 10
    [[languages.ko.menu.main]]
      identifier = "search"
      name = "Search"
      url = "/search/"
      weight = 20
    [[languages.ko.menu.main]]
      identifier = "tags"
      name = "Tags"
      url = "/tags/"
      weight = 30
